apiVersion: v1
kind: Service
metadata:
  name: saleor-lb
  labels:
    env: dev
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: saleor
  ports:
    - name: saleor-port
      targetPort: 8000
      port: 31000