---
apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: redis-claim
  namespace: dev
spec:
  storageClassName: managed-premium
  accessModes: ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    env: dev
    app: redis
  namespace: dev
spec:
  containers:
    - name: redis-container
      image: library/redis:5.0-alpine
      ports:
        - containerPort: 6379
      volumeMounts:
        - name: data-vol
          mountPath: /data
  volumes:
    - name: data-vol
      persistentVolumeClaim:
        claimName: redis-claim
