apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    env: dev
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - name: redis-port
      targetPort: 6379
      port: 31110