apiVersion: v1
kind: Service
metadata:
  name: db-Cluster
  labels:
    env: dev
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: db-port
      targetPort: 5432
      port: 31100